title: Jeff Owino
description: I am an accomplished Senior Machine Learning Engineer with advanced studies in machine learning, AI, and applied statistics, holding a master's degree and a Ph.D. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jeff Owino  # add your name
author-img: profile.png # add your photo
about-author: I am an accomplished Senior Machine Learning Engineer with advanced studies in machine learning, AI, and applied statistics, holding a master's degree and a Ph.D. My extensive educational background has equipped me with a deep understanding of the theoretical foundations and practical applications of cutting-edge technologies. Leveraging this knowledge, I excel in building robust and intelligent systems that drive innovation and deliver exceptional results.
social-twitter: JEFFOWINO3
social-facebook: # add your Facebook handle
social-github: jeffowino # add your Github handle
social-linkedin: jeff-owino-b0403a148 # add your Linkedin handle
social-email: # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics:  Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
